# Generated by Django 6.0.3 on 2026-05-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventosocial_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosocial',
            name='link_comprovacao',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
