# Generated by Django 6.0.3 on 2026-06-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventosocial_link_comprovacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosocial',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
